
- name: Restart Multiple WebSphere JVMs
  hosts: websphere_Testservers
  become: yes
  vars:
    was_profile_path: /Was/IBM/WebSphere/AppServer/profiles/AppSrv01
    was_username: "{{ lookup('env', 'WAS9_USERNAME') }}"
    was_password: "{{ lookup('env', 'WAS9_PASSWORD') }}"
    jvm_list:
      - diger
      - emk4a
      - emk4b
      - guv
      - guv_jpa2.0_1
      - test83_iso

  tasks:

    - name: Stop JVMs
      shell: >
        timeout 120 {{ was_profile_path }}/bin/stopServer.sh {{ item }}
        -username {{ was9_username }} -password {{ was9_password }}
      loop: "{{ jvm_list }}"
      register: stop_results
      ignore_errors: yes

    - name: Kontrol JVM'ler durdu mu?
      shell: ps -ef | grep -i {{ item }} | grep -v grep
      loop: "{{ jvm_list }}"
      register: stop_check
      changed_when: false
      failed_when: stop_check.results[loop.index0].rc == 0
      ignore_errors: false

    - name: Bekleniyor (her JVM sonrasi 15 saniye)
      pause:
        seconds: 300
      loop: "{{ jvm_list }}"

    - name: Start JVMs
      shell: "{{ was_profile_path }}/bin/startServer.sh {{ item }}"
      loop: "{{ jvm_list }}"
      register: start_results
      ignore_errors: yes

    - name: Kontrol JVM'ler başladi mi?
      shell: ps -ef | grep -i {{ item }} | grep -v grep
      loop: "{{ jvm_list }}"
      register: start_check
      changed_when: false
      failed_when: start_check.results[loop.index0].rc != 0
      ignore_errors: false